services:
  ipx:
    build:
      context: .
      tags:
        - ipx-server:lastest
    image: ipx-server
    restart: unless-stopped
    networks:
      - coolify
    environment:
      - TZ=${TZ}
      - IPX_HTTP_DOMAINS=${IPX_HTTP_DOMAINS}
      - IPX_HTTP_MAX_AGE=${IPX_HTTP_MAX_AGE}
      - IPX_FS_DIR=${IPX_FS_DIR}
      - IPX_FS_MAX_AGE=${IPX_FS_MAX_AGE}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_PORT=${S3_PORT}
      - S3_USE_SSL=${S3_USE_SSL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - CONSOLA_LEVEL=${CONSOLA_LEVEL}
      - NODE_ENV=${NODE_ENV}
      - IPX_MAX_CONCURRENT=${IPX_MAX_CONCURRENT}
    volumes:
      - ./public:/usr/src/app/public
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.http.routers.ipx-http.entryPoints=http
      - traefik.http.routers.ipx-http.rule=Host(`ipx.vandal.services`) && PathPrefix(`/`)
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.ipx-http.middlewares=redirect-to-https
      - traefik.http.routers.ipx-https.entryPoints=https
      - traefik.http.routers.ipx-https.rule=Host(`ipx.vandal.services`) && PathPrefix(`/`)
      - traefik.http.routers.ipx-https.tls=true
      - traefik.http.routers.ipx-https.tls.certresolver=letsencrypt
      - traefik.http.services.ipx.loadbalancer.server.port=3000
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1"
          memory: 2048M

networks:
  coolify:
    external: true
