services:
  ipx:
    build:
      context: .
      tags:
        - ipx-server:lastest
    image: ipx-server
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - IPX_HTTP_DOMAINS=${IPX_HTTP_DOMAINS}
      - IPX_HTTP_MAX_AGE=${IPX_HTTP_MAX_AGE}
      - IPX_FS_DIR=${IPX_FS_DIR}
      - IPX_FS_MAX_AGE=${IPX_FS_MAX_AGE}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_PORT=${S3_PORT}
      - S3_USE_SSL=${S3_USE_SSL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - CONSOLA_LEVEL=${CONSOLA_LEVEL}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./public:/usr/src/app/public
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
